<style>
.tm-highlight {
  color: #c94c4c;
}
</style>
<?php   
$var = Mage::getSingleton('core/session')->getSomeSessionVar();

list($trxid, $accountNumber, $iban, $bic, $beneficiary, $bank) = explode("|", $var['data']);
$order = $var['order'];
$formattedPrice = Mage::helper('core')->currency($order->grand_total, true, false);

if(Mage::app()->getLocale()->getLocaleCode() != 'nl_NL') {
?>

    <div class="bankwire-info">
        <h4>Thank you for ordering in our webshop!</h4>
        <p>
            You will receive your order as soon as we receive payment from the bank. <br>
            Would you be so friendly to transfer the total amount of <?= $formattedPrice?> to the bankaccount <b class="tm-highlight"><?= $iban ?></b> in name of <?= $beneficiary ?>*?
        </p>
        <p>&nbsp; </p>
        <p>
            State the payment feature <b><?= $trxid ?></b>, this way the payment can be automatically processed.<br>
            As soon as this happens you shall receive a confirmation mail on <?= $order->customer_email ?>.
        </p>
        <p>
        <p>&nbsp; </p>
        
        <p>If it is necessary for payments abroad, then the BIC code from the bank <span class="tm-highlight"><?= $bic ?></span> and the name of the bank is <?= $bank ?>.</p>
        <p>&nbsp; </p>
        <p>
            <i>* Payment for our webstore is processed by TargetMedia. TargetMedia is certified as a Collecting Payment Service Provider by Currence. This means we set the highest security standards when is comes to security of payment for you as a customer and us as a webshop.</i>
        </p>
    </div>
<?php }

else { ?>
    <div class="bankwire-info">
        <h4>Bedankt voor uw bestelling in onze webwinkel!</h4>
        <p>
        U ontvangt uw bestelling zodra we de betaling per bank ontvangen hebben. 
        Zou u zo vriendelijk willen zijn het totaalbedrag van <?= $formattedPrice?> 
        over te maken op bankrekening <b class="tm-highlight"><?= $iban ?></b> t.n.v. <?= $beneficiary ?>* ?
        </p>
        <p>&nbsp; </p>
        <p>
        Vermeld daarbij als betaalkenmerk <b><?= $trxid ?></b>, zodat de betaling automatisch verwerkt kan worden. 
        Zodra dit gebeurd is ontvangt u een mail op <?= $order->customer_email ?> ter bevestiging. 
        </p>
        <p>
        <p>&nbsp; </p>
        
        <p>Mocht het nodig zijn voor betalingen vanuit het buitenland, dan is de BIC code van de bank <span class="tm-highlight"><?= $bic ?></span> en de naam van de bank is '<?= $bank ?>'.
        Zorg ervoor dat u kiest voor kosten in het buitenland voor eigen rekening (optie: OUR), anders zal het bedrag wat binnenkomt te laag zijn.
        
       </p>
        <p>&nbsp; </p>
        <p>
            <i>*De betalingen voor onze webwinkel worden verwerkt door TargetMedia. TargetMedia is gecertificeerd als Collecting Payment Service Provider door Currence. Dat houdt in dat zij aan strenge eisen dient te voldoen als het gaat om de veiligheid van de betalingen voor jou als klant en ons als webwinkel.</i>
        </p>
    </div>
<?php } ?>