<?php
$_code=$this->getMethodCode();
?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_bank_id">Bank <span class="required">*</span></label><br>
                <select id="<?php echo $_code ?>_bank_id" name="payment[bank_id]" class="required-entry">
              	<?php
				foreach ($this->getBanks() as $id => $name) {
			    	echo "<option value=\"".$id."\">".$name."</option>\r\n";
			        }
                ?>
                </select>
            </div>
        </li>
    </ul>
</fieldset>
