<?php
$_code=$this->getMethodCode();
?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_bank_id">Land <span class="required">*</span></label><br>
                <select id="<?php echo $_code ?>_bank_id" name="payment[country_id]" class="required-entry">
                <option value="49">Deutschland</option>
                <option value="43">Osterreich</option>
                <option value="41">Die Schweiz</option>
                </select>
            </div>
        </li>
    </ul>
</fieldset>
